### PR TITLE
fix: incorrect return types of `keys`

### LINKED ISSUE #226: Type error for plugin `keys` field
Passing a function to `NvPluginSpec.keys` for example:
```lua
  {
    "folke/which-key.nvim",
    keys = function()
      return { "<leader>" }
    end,
  }
```
Raises the diagnostic error:
```sh
Diagnostics:
Cannot assign `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` to `(string|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?`.
- `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match `(string|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?`
- `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match any subtypes in `(string|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?`
- Type `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match `nil`
- Type `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match `fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]`
- Type `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match `LazyKeymaps[]`
- Type `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match `string[]`
- Type `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` cannot match `string` [assign-type-mismatch]
```
Not really sure what's wrong here

### PR DESCRIPTION
**Pull request by lucario387**
Fix #226

### CODE REVIEW

File: nvchad_types/plugins.lua [hunk 1]
```diff
@@ -32,7 +34,7 @@
 ---       {"foo", "bar", desc = "Some keymaps", mode = {"n", "i"}}
 ---     }
 --- ```
----@field keys? string|string[]|LazyKeymaps[]|fun(_:LazyPlugin, keys:string[]):(string|LazyKeymaps)[] 
+---@field keys? string|string[]|LazyKeymaps[]|fun(_:LazyPlugin, keys:string[]):PluginKeyReturnTypes
```
Comment (KorigamiK) [inline nvchad_types/plugins.lua:37]: But it's weird how you can't mention the type inline here

Comment (lucario387) [reply nvchad_types/plugins.lua:37]: If it works it works :smile:
